project:
  type: book
  output-dir: docs



book:
  title: "El Corrido de Gregorio Cortez NER and Mapping book"
  author: "Diane Lopez"
  date: "2/6/2023"
  repo-url: https://github.com/dianita956/mapping-ner
  repo-branch: main
  chapters:
    - index.qmd
    - 01webscrapBS.qmd
    - 02textfile_to_jsonfile.qmd
    - 03NER_SpacyCustomModel.qmd
    - 04GregCortezMap.qmd
    - 05references.qmd 

bibliography: references.bib 

format:
  html:
    code-fold: true
    toc: true
    theme: cosmo
    date-modified: now